# Python ile Sıfırdan MultiLayer Perceptron Tasarımı

## 1) Ağırlık ve Bias değerlerini Oluşturma

In [1]:
import numpy as np

class ANN:
    
    def __init__(self,x_train,y_train,x_test,y_test):

        self.x_train= x_train
        self.y_train= y_train
        self.x_test= x_test
        self.y_test= y_test
    
    def initlazition_w_b(self,node_num_list:list=None):

        #http://www.derinogrenme.com/2018/06/28/geri-yayilim-algoritmasina-matematiksel-yaklasim/
        
        weights={}
        
        N=self.y_test[0].size#Getting the size of the input
        
        for i in range(node_num_list.size):

            M=node_num_list[i]
            
            weights['w'+str(i+1)] = np.random.random_sample((N,M))# y =x.w +b = (1,N) * (N,M) +(1,M)
                                                                  # N =bir_önceki_katman_nöronların_sayısı
                                                                  # M =simdik_katmandaki_nöron_sayısı 
            weights['b'+str(i+1)] = np.full((1,M),0)              # (1,M)
            
            N=M
            
        
        return weights
            
            

        

**Artık modelimizin değerlerini rastgele değerler ile oluşturduk. Şimdi Multilayer Perceptronu oluşturabiliriz.**

In [2]:

y_test = np.array([[0.4,1.8,-0.7]])

model=ANN([],[],[],y_test)


ag_yapisi = np.array([4,4,1])

degerler=model.initlazition_w_b(ag_yapisi) # 3 - 4 - 4 - 1 : 2 Gizli katman ve 1 çıkış katmanı mevcut.


**Oluşturduğumuz ağı görselleştirelim.**

In [3]:
#Görselleştirme

print('G İ R D İ L E R :',y_test)
print('\n','----O----'*y_test.size,'Giriş Katmanındaki Nöronlar ','\n')


for i in range(ag_yapisi.size):
    
    print('w',str(i+1),' :\n',degerler['w'+str(i+1)])

    print('b',str(i+1),':\n',degerler['b'+str(i+1)])
    
    if i ==ag_yapisi.size-1:
        
        print('\n','----O----'*ag_yapisi[i],'Çıkış Katmanındaki Nöron   ')
        break# en sonda döngüden çık
        
    print('\n','----O----'*ag_yapisi[i],'  ',str(i+1),'.Gizli Katmandaki Nöronlar   ')
    


G İ R D İ L E R : [[ 0.4  1.8 -0.7]]

 ----O--------O--------O---- Giriş Katmanındaki Nöronlar  

w 1  :
 [[0.67894508 0.43558046 0.04506979 0.72259728]
 [0.83129866 0.53633875 0.14902765 0.23275572]
 [0.99172507 0.67172987 0.10533728 0.18202701]]
b 1 :
 [[0 0 0 0]]

 ----O--------O--------O--------O----    1 .Gizli Katmandaki Nöronlar   
w 2  :
 [[0.13546758 0.60438969 0.6855248  0.30192678]
 [0.96701878 0.65453056 0.08527388 0.54781393]
 [0.4468146  0.33310474 0.89529389 0.49673917]
 [0.48813676 0.2138491  0.20602946 0.30715937]]
b 2 :
 [[0 0 0 0]]

 ----O--------O--------O--------O----    2 .Gizli Katmandaki Nöronlar   
w 3  :
 [[0.96914894]
 [0.11136462]
 [0.75994862]
 [0.25792219]]
b 3 :
 [[0]]

 ----O---- Çıkış Katmanındaki Nöron   


![title](img/resim1.png)


## 2)Aktivasyon Fonksiyonları Oluşturma

In [4]:
import numpy as np

class ANN:
    
    
    def __init__(self,x_train,y_train,x_test,y_test):

        self.x_train= x_train
        self.y_train= y_train
        self.x_test= x_test
        self.y_test= y_test
    
    
    def initlazition_w_b(self,node_num_list:list=None):
  
        weights={}
        
        N=self.y_test[0].size#Getting the size of the input
        
        for i in range(node_num_list.size):

            M=node_num_list[i]
            
            weights['w'+str(i+1)] = np.random.random_sample((N,M))
            
            weights['b'+str(i+1)] = np.full((1,M),0)              
            
            N=M
    
        return weights
                     
        
    def activation_function(self,x,name='Sigmoid',derivative=False):#default: Sigmoid Function,derivative =False
        
        if name =='Threshold' and derivative==False:
            
            output = int(x>=0) # Threshold(x)
         
        elif name =='Threshold' and derivative==True:
            
            output = 0 # Threshold'(x)
            
        elif name =='Sigmoid' and derivative==False:
            
            output = 1 / (1 + np.exp(-x)) # s(x)
        
        elif name =='Sigmoid' and derivative==True:
            
            output = (1 / (1 + np.exp(-x))) * (1-(1 / (1 + np.exp(-x)))) # s'(x)=s(x) * (1 - s(x))
        
        elif name =='Tanh' and derivative==False:# tanh is sometimes called hyperbolic tangent
            
            output = np.sinh(x)/np.cosh(x)  # tanh(x)
        
        elif name =='Tanh' and derivative==True:
            
            output = 1 -np.power(np.sinh(x)/np.cosh(x),2) # tanh'(x) = 1- (tanh(x)^2)
            
        elif name =='ReLU' and derivative==False:# ReLU = Rectified Linear Unit
            
            output = np.maximum(0,x) #ReLU(x)
        
        elif name =='ReLU' and derivative==True:
            
            output = int(x >= 0 ) # ReLU'(x) = { 0  if x < 0,
                                  #             1  if x >= 0  }
                
        elif name =='leakyRELU' and derivative==False:
            
            output = np.maximum(0.01 * x, x) #leaky_ReLU'(x) 
            
        elif name =='leakyRELU'  and derivative==True:
            
            output = 0.01+(int(x >= 0 )*0.99) # leaky_ReLU'(x) = {  0.01   if x < 0,
                                              #                     1      if x >= 0  }
        elif name =='Swish' and derivative ==False:
            
            output = np.dot(x, 1 / (1 + np.exp(-x))) # Swish(x)
        
        elif name =='Swish' and derivative ==True:
            
            output = (1 + np.exp(-x)) + ((np.exp(-x)*x) / np.power(1 + np.exp(-x),2)) # Swish'(x)
        
        elif name =='Softmax' and derivative ==False:
            
            output ='Yapılmadı Araştır'  # Swish(x)
        
        elif name =='Softmax' and derivative ==True:
            
            output ='Yapılmadı Araştır'  # Swish'(x)
                
        return output
    


In [5]:

y_test = np.array([[0.4,1.8,-0.7]])

model=ANN([],[],[],y_test)

model.activation_func(-2,name='leakyRELU',derivative=True) # bu fonksiyonu incele

AttributeError: 'ANN' object has no attribute 'activation_func'

# 3)Katman mimarisi

In [6]:
import numpy as np

class ANN:
    
    
    def __init__(self,x_train,y_train,x_test,y_test):

        self.x_train= x_train
        self.y_train= y_train
        self.x_test= x_test
        self.y_test= y_test
    
    
    def initlazition_w_b(self,node_num_list:list=None):
  
        weights={}
        
        N=self.y_test[0].size#Getting the size of the input
        
        for i in range(node_num_list.size):

            M=node_num_list[i]
            
            weights['w'+str(i+1)] = np.random.random_sample((N,M))
            
            weights['b'+str(i+1)] = np.full((1,M),0)              
            
            N=M
    
        return weights
                     
        
    def activation_function(self,x,name='Sigmoid',derivative=False):#default: Sigmoid Function,derivative =False
        
        if name =='Threshold' and derivative==False:
            
            output = int(x>=0) # Threshold(x)
         
        elif name =='Threshold' and derivative==True:
            
            output = 0 # Threshold'(x)
            
        elif name =='Sigmoid' and derivative==False:
            
            output = 1 / (1 + np.exp(-x)) # s(x)
        
        elif name =='Sigmoid' and derivative==True:
            
            output = (1 / (1 + np.exp(-x))) * (1-(1 / (1 + np.exp(-x)))) # s'(x)=s(x) * (1 - s(x))
        
        elif name =='Tanh' and derivative==False:# tanh is sometimes called hyperbolic tangent
            
            output = np.sinh(x)/np.cosh(x)  # tanh(x)
        
        elif name =='Tanh' and derivative==True:
            
            output = 1 -np.power(np.sinh(x)/np.cosh(x),2) # tanh'(x) = 1- (tanh(x)^2)
            
        elif name =='ReLU' and derivative==False:# ReLU = Rectified Linear Unit
            
            output = np.maximum(0,x) #ReLU(x)
        
        elif name =='ReLU' and derivative==True:
            
            output = int(x >= 0 ) # ReLU'(x) = { 0  if x < 0,
                                  #             1  if x >= 0  }
                
        elif name =='leakyRELU' and derivative==False:
            
            output = np.maximum(0.01 * x, x) #leaky_ReLU'(x) 
            
        elif name =='leakyRELU'  and derivative==True:
            
            output = 0.01+(int(x >= 0 )*0.99) # leaky_ReLU'(x) = {  0.01   if x < 0,
                                              #                     1      if x >= 0  }
        elif name =='Swish' and derivative ==False:
            
            output = np.dot(x, 1 / (1 + np.exp(-x))) # Swish(x)
        
        elif name =='Swish' and derivative ==True:
            
            output = (1 + np.exp(-x)) + ((np.exp(-x)*x) / np.power(1 + np.exp(-x),2)) # Swish'(x)
        
        elif name =='Softmax' and derivative ==False:
            
            output ='Yapılmadı Araştır'  # Swish(x)
        
        elif name =='Softmax' and derivative ==True:
            
            output ='Yapılmadı Araştır'  # Swish'(x)
                
        return output
    

    def layer_architecture(self,node_num_list:np.array=None,activation_function_list:np.array=None): # [node_1]
        
        return self.initlazition_w_b(node_num_list),activation_function_list
    
    

## 4)İleri besleme ( Feedforwad )

In [7]:
import numpy as np

class ANN:
    
    
    def __init__(self, X_train, X_test, y_train, y_test):

        self.X_train= X_train
        self.X_test= X_test
        self.y_train= y_train
        self.y_test= y_test
    
    
    def initlazition_w_b(self,node_num_list:list=None):
        # example:
        # y =x.w +b = (1,N) * (N,M) +(1,M)
        weights={}
        
        N=self.y_test[0].size #Getting the size of the input
        
        for i in range(node_num_list.size):

            M=node_num_list[i]
            
            weights['w'+str(i+1)] = np.random.random_sample((N,M))
            
            weights['b'+str(i+1)] = np.full((1,M),0)              
            
            N=M
    
        return weights
                     
        
    def activation_function(self,x,name='Sigmoid',derivative=False):#default: Sigmoid Function,derivative =False
        
        if name =='Threshold' and derivative==False:
            
            output = int(x>=0) # Threshold(x)
         
        elif name =='Threshold' and derivative==True:
            
            output = 0 # Threshold'(x)
            
        elif name =='Sigmoid' and derivative==False:
            
            output = 1 / (1 + np.exp(-x)) # s(x)
        
        elif name =='Sigmoid' and derivative==True:
            
            output = (1 / (1 + np.exp(-x))) * (1-(1 / (1 + np.exp(-x)))) # s'(x)=s(x) * (1 - s(x))
        
        elif name =='Tanh' and derivative==False:# tanh is sometimes called hyperbolic tangent
            
            output = np.sinh(x)/np.cosh(x)  # tanh(x)
        
        elif name =='Tanh' and derivative==True:
            
            output = 1 -np.power(np.sinh(x)/np.cosh(x),2) # tanh'(x) = 1- (tanh(x)^2)
            
        elif name =='ReLU' and derivative==False:# ReLU = Rectified Linear Unit
            
            output = np.maximum(0,x) #ReLU(x)
        
        elif name =='ReLU' and derivative==True:
            
            output = int(x >= 0 ) # ReLU'(x) = { 0  if x < 0,
                                  #             1  if x >= 0  }
                
        elif name =='leakyRELU' and derivative==False:
            
            output = np.maximum(0.01 * x, x) #leaky_ReLU'(x) 
            
        elif name =='leakyRELU'  and derivative==True:
            
            output = 0.01+(int(x >= 0 )*0.99) # leaky_ReLU'(x) = {  0.01   if x < 0,
                                              #                     1      if x >= 0  }
        elif name =='Swish' and derivative ==False:
            
            output = np.dot(x, 1 / (1 + np.exp(-x))) # Swish(x)
        
        elif name =='Swish' and derivative ==True:
            
            output = (1 + np.exp(-x)) + ((np.exp(-x)*x) / np.power(1 + np.exp(-x),2)) # Swish'(x)
        
        elif name =='Softmax' and derivative ==False:
            
            output ='Yapılmadı Araştır'  # Swish(x)
        
        elif name =='Softmax' and derivative ==True:
            
            output ='Yapılmadı Araştır'  # Swish'(x)
                
        return output
    

    def layer_architecture(self,node_num_list:np.array=None,activation_function_list:np.array=None): # [node_1]
        
        return  self.initlazition_w_b(node_num_list) , activation_function_list
    

    # w_b, activation_function_list = ANN.layer_architecture(node_num_list,activation_function_list)
    def feedforwad(self,w_b,activation_function_list):#bu fonksiyonu oluşturma amacım elinizdeki önemli ağırlıklar var ise bunarı direk kullanın diye
        
        a = self.X_train#input
        
        for i in range(activation_function_list.size):
            #print( a.shape,w_b['w'+str(i+1)].shape) #size check 
            
            z = np.matrix.dot(a , w_b['w'+str(i+1)] )  +  w_b['b'+str(i+1)] # Indexes for weights and bias numbers start at 1
            
            a = self.activation_function(z,name =activation_function_list[i])
            
        
        return a
    
    
            
        
    
    

In [8]:
X_train =np.array([[0.05,0.1]])
X_test =np.array([[0.004,0.7]]) 
y_train = np.array([[0.01,0.99]])
y_test = np.array([[0.001,0.59]])


# ADIM 1 :Model Oluştur
model = ANN(X_train, X_test, y_train, y_test)


# ADIM 2 :Katman Mimarisini Oluştur
node_num_list = np.array([4,3,2])

activation_function_list = np.array(['ReLU','Sigmoid','Sigmoid'])

w_b, activation_function_list = model.layer_architecture(node_num_list,activation_function_list)


# ADIM 3 :İleri Yayılım Oluştur
model.feedforwad(w_b,activation_function_list)



array([[0.7722644 , 0.76854212]])

**Neden layer_architecture içinde feedforwad yapmadım ? Çünkü kurcağımız modele benzer elimizde eğitilmiş sistemin ağırlık ve bias değerleri mevcut ise bu değerler ile başlatmak bize hem zamandan kar hemde daha iyi bir sonuç verme ihtimali oluşturuyor.**


**Bir Örnek Yapalım :**

In [9]:
X_train =np.array([[0.05,0.1]])
X_test =np.array([[0.004,0.7]]) 
y_train = np.array([[0.01,0.99]])
y_test = np.array([[0.001,0.59]])



model = ANN(X_train, X_test, y_train, y_test) 

#Hazır Ağırlıklar
weights ={'b1':np.array([[0.35,0.35]]),
          'b2':np.array([[0.6,0.6]]),
          'w1':np.array([[0.15,0.25],
                         [0.20,0.30]]),
          'w2':np.array([[0.40,0.50],
                         [0.45,0.55]]),
         }

#https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/
   
model.feedforwad(weights,np.array(['Sigmoid','Sigmoid']))

array([[0.75136507, 0.77292847]])

## 5)Hata Fonksiyonu ( Loss Function/Cost Function  )

The loss function computes the error for a single training example. The cost function is the average of the loss functions of the entire training set.

In most learning networks, error is calculated as the difference between the actual output and the predicted output.


![title](img/J.PNG)


The function that is used to compute this error is known as Loss Function J(.). Different loss functions will give different errors for the same prediction, and thus have a considerable effect on the performance of the model. One of the most widely used loss function is mean square error, which calculates the square of difference between actual value and predicted value. Different loss functions are used to deal with different type of tasks, i.e. regression and classification.

**Loss Functions:**

Thus, loss functions are helpful to train a neural network. Given an input and a target, they calculate the loss, i.e difference between output and target variable. Loss functions fall under four major category:

***Regressive loss functions***:
They are used in case of regressive problems, that is when the target variable is continuous. Most widely used regressive loss function is Mean Square Error. Other loss functions are:
1. Absolute error — measures the mean absolute value of the element-wise difference between input;
2. Smooth Absolute Error — a smooth version of Abs Criterion.

***Classification loss functions***:
The output variable in classification problem is usually a probability value f(x), called the score for the input x. Generally, the magnitude of the score represents the confidence of our prediction. The target variable y, is a binary variable, 1 for true and -1 for false. 
On an example (x,y), the margin is defined as yf(x). The margin is a measure of how correct we are. Most classification losses mainly aim to maximize the margin. Some classification algorithms are:
1. Binary Cross Entropy 
2. Negative Log Likelihood
3. Margin Classifier
4. Soft Margin Classifier

***Embedding loss functions***:
It deals with problems where we have to measure whether two inputs are similar or dissimilar. Some examples are:
1. L1 Hinge Error- Calculates the L1 distance between two inputs.
2. Cosine Error- Cosine distance between two inputs.

https://medium.com/data-science-group-iitr/loss-functions-and-optimization-algorithms-demystified-bb92daff331c

**[İmportant !]**  http://christopher5106.github.io/deep/learning/2016/09/16/about-loss-functions-multinomial-logistic-logarithm-cross-entropy-square-errors-euclidian-absolute-frobenius-hinge.html

**[İmportant !]**  https://github.com/torch/nn/blob/master/doc/criterion.md

## 6)Geri yayılım ( Backpropagation )

## 7)Model Optimizasyon ( Model Optimizers  )

The optimizer is a search technique, which is used to update weights in the model.

**SGD**: Stochastic Gradient Descent, with support for momentum.

**RMSprop**: Adaptive learning rate optimization method proposed by Geoff Hinton.

**Adam**: Adaptive Moment Estimation (Adam) that also uses adaptive learning rates.

---

We used three first order optimisation functions and studied their effect.

**1)** Stochastic Gradient Decent

**2)** Adagrad

**3)** Adam

***Gradient Descent*** calcultes gradient for the whole dataset and updates values in direction opposite to the gradients until we find a local minima. Stochastic Gradient Descent performs a parameter update for each training example unlike normal Gradient Descent which performs only one update. Thus it is much faster. Gradient Decent algorithms can further be improved by tuning important parametes like momentum, learning rate etc.

***Adagrad*** is more preferrable for a sparse data set as it makes big updates for infrequent parameters and small updates for frequent parameters. It uses a different learning Rate for every parameter θ at a time step based on the past gradients which were computed for that parameter. Thus we do not need to manually tune the learning rate.

***Adam*** stands for Adaptive Moment Estimation. It also calculates different learning rate. Adam works well in practice, is faster, and outperforms other techniques.

***Stochastic Gradient Decent was much faster than the other algorithms but the results produced were far from optimum. Both, Adagrad and Adam produced better results that SGD, but they were computationally extensive. Adam was slightly faster than Adagrad. Thus, while using a particular optimization function, one has to make a trade off between more computation power and more optimum results.***

https://medium.com/data-science-group-iitr/loss-functions-and-optimization-algorithms-demystified-bb92daff331c

**[İmportant !]**  http://christopher5106.github.io/deep/learning/2016/09/16/about-loss-functions-multinomial-logistic-logarithm-cross-entropy-square-errors-euclidian-absolute-frobenius-hinge.html

**[İmportant !]**  https://github.com/torch/nn/blob/master/doc/criterion.md