# Python ile Sıfırdan MultiLayer Perceptron Tasarımı

## 1) Ağırlık ve Bias değerlerini Oluşturma

In [1]:
import numpy as np

class ANN:
    
    def __init__(self,x_train,y_train,x_test,y_test):

        self.x_train= x_train
        self.y_train= y_train
        self.x_test= x_test
        self.y_test= y_test
    
    def initlazition_w_b(self,node_num_list:list=None):

        node_list =np.append(self.y_test[0].size,node_num_list) #giriş katmanı katmandan sayılmıyor 
                                                                #fakat ağırlık matrislerinin boyutlarını etkilediği için ekledim
 
        #http://www.derinogrenme.com/2018/06/28/geri-yayilim-algoritmasina-matematiksel-yaklasim/
        weights={}
        for i in range(node_list.size-1):#çünkü giriş katmanı bir katman sayılmıyor
            # X = [ . .  .    . . .] satır olarak alıyoruz
            #
            weights['w'+str(i+1)] = np.random.random_sample((node_list[i],node_list[i+1]))# y =x.w +b = (1,N) * (N,M) +(1,M)
                                                                # N =simdik_katmandaki_nöron_sayısı 
                                                                # M =bir_önceki_katman_nöronların_sayısı
                                                                # boyutlar şöyle= (M,N)
            weights['b'+str(i+1)] = np.full((1,node_list[i+1]),0) # (1,N)
        
        return weights
            
            

        

**Artık modelimizin değerlerini rastgele değerler ile oluşturduk. Şimdi Multilayer Perceptronu oluşturabiliriz.**

In [2]:

y_test = np.array([[0.4,1.8]])

model=ANN([],[],[],y_test)


ag_yapisi = np.array([4,3,1])

degerler=model.initlazition_w_b(ag_yapisi) # 2 - 4 - 3 - 1 : 2 Gizli katman ve 1 çıkış katmanı mevcut.


**Oluşturduğumuz ağı görselleştirelim.**

In [3]:
#Görselleştirme

print('G İ R D İ L E R :',y_test)
print('\n','----O----'*y_test.size,'Giriş Katmanındaki Nöronlar ','\n')


for i in range(ag_yapisi.size):
    
    print('w',str(i+1),' :\n',degerler['w'+str(i+1)])

    print('b',str(i+1),':\n',degerler['b'+str(i+1)])
    
    if i ==ag_yapisi.size-1:
        
        print('\n','----O----'*ag_yapisi[i],'Çıkış Katmanındaki Nöron   ')
        break# en sonda döngüden çık
        
    print('\n','----O----'*ag_yapisi[i],'  ',str(i+1),'.Gizli Katmandaki Nöronlar   ')
    


G İ R D İ L E R : [[0.4 1.8]]

 ----O--------O---- Giriş Katmanındaki Nöronlar  

w 1  :
 [[0.56541887 0.10971356 0.6855159  0.57315279]
 [0.72007418 0.91532905 0.95591631 0.96631244]]
b 1 :
 [[0 0 0 0]]

 ----O--------O--------O--------O----    1 .Gizli Katmandaki Nöronlar   
w 2  :
 [[0.9530958  0.05384011 0.96843019]
 [0.60641561 0.37769098 0.13020985]
 [0.31944734 0.24080147 0.43404571]
 [0.39351993 0.99357539 0.41913688]]
b 2 :
 [[0 0 0]]

 ----O--------O--------O----    2 .Gizli Katmandaki Nöronlar   
w 3  :
 [[0.16222872]
 [0.08440133]
 [0.83062473]]
b 3 :
 [[0]]

 ----O---- Çıkış Katmanındaki Nöron   
